#!/bin/bash

if [ "setup" == $1 ]; then
    echo "Running setup"
    python3 -m venv venv
    pip install -r requirements.txt
    exit;
fi

if [ "$1" == "upgrade" ]; then
    echo "Upgrading plan"
    python -c "from updatePlan import upgrade; upgrade('$2', '$3')"

fi

if [ "$1" == "downgrade" ]; then
    echo "Downgrading plan"   
    python -c "from updatePlan import downgrade; downgrade('$2', '$3')"

fi
