#!/bin/bash

# Before create a virtual environment

if [ "setup" == $1 ]; then
    echo "Running setup"
    pip install -r requirements.txt
    # The following code run the test and make a coverage report
    pytest
    coverage report
    exit;
fi

if [ "$1" == "upgrade" ]; then
    echo " ### Upgrading plan ###"
    python -c "from update_plan import upgrade; upgrade('$2', '$3')"

fi

if [ "$1" == "downgrade" ]; then
    echo "### Downgrading plan ###"   
    python -c "from update_plan import downgrade; downgrade('$2', '$3')"

fi
